# Buildpacks to include in builder
[[buildpacks]]
uri = "../arnoldc-buildpack"

[stack]
id = "dev.jaywilson.stacks.alpine"
run-image = "harbor.20.112.44.2.getmoss.site/library/ac-stack-run:alpine"
build-image = "harbor.20.112.44.2.getmoss.site/library/ac-stack-build:alpine"