
# kubectl create secret docker-registry tutorial-registry-credentials --docker-username=jay --docker-password=Shark68! --docker-server=https://harbor.52.143.84.12.getmoss.site/  --namespace default --dry-run=client -o yaml | pbcopy

apiVersion: v1
kind: Secret
metadata:
  name: basic-git-user-pass
  annotations:
    kpack.io/git: https://git.52.143.84.12.getmoss.site
type: kubernetes.io/basic-auth
stringData:
  username: gitadmin
  password: GitIsGreat1!
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tutorial-service-account
  namespace: default
secrets:
- name: tutorial-registry-credentials
- name: basic-git-user-pass
imagePullSecrets:
- name: tutorial-registry-credentials
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: arnoldc
spec:
 serviceAccountRef:
    name: tutorial-service-account
    namespace: default
 sources:
  - image: us-central1-docker.pkg.dev/playground-s-11-eb170af4/tbs/arnoldc-buildpack
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: arnoldc
spec:
  serviceAccountRef:
    name: tutorial-service-account
    namespace: default
  id: "dev.jaywilson.stacks.alpine"
  buildImage:
    image: "us-central1-docker.pkg.dev/playground-s-11-eb170af4/tbs/ac-stack-build:alpine"
  runImage:
    image: "us-central1-docker.pkg.dev/playground-s-11-eb170af4/tbs/ac-stack-run:alpine"
--- 
apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: arnoldc-builder
  namespace: default
spec:
  serviceAccountName: tutorial-service-account
  tag: us-central1-docker.pkg.dev/playground-s-11-eb170af4/tbs/pack-arnoldc-builder:latest
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  # order:
  # - group:
  #   - id: dev.jaywilson.stacks/library/ac-stack
