apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: arnoldc-builder
  namespace: default
spec:
  serviceAccount: harbor-service-account
  tag: harbor.52.143.84.12.getmoss.site/open/arnoldc-builder:alpine
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
